name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 安装rcedit
      run: |
        npm install -g rcedit

    - name: 复制需要打包的文件
      run: |
        mkdir -p dakumi
        cp -r asset dakumi/
        cp -r function dakumi/
        cp -r objact dakumi/
        cp -r room dakumi/
        cp -r thread dakumi/
        cp conf.lua dakumi/
        cp main.lua dakumi/
        cp the_require.lua dakumi/
        cp icon.ico dakumi/
        cp LXGWNeoXiHei.ttf dakumi/
        cp LXGWNeoXiHei_LICENSE.md dakumi/

    - name: 打包游戏
      run: |
        cd dakumi
        Compress-Archive -Path * -DestinationPath ../game.zip -Force
        cd ..
        cmd.exe /c "copy /b test\love.exe+game.zip test\dakumi_editor.exe"
        cp hit_sound.ogg test/
        cp 7z.exe test/
        cp 7z.dll test/
        cp language.txt test/

    - name: 使用rcedit修改图标
      run: |
        rcedit test/dakumi_editor.exe --set-icon icon.ico

    - name: 上传制品
      uses: actions/upload-artifact@v4
      with:
        name: dakumi_editor_windows
        path: test